# Generated by Django 2.2.13 on 2020-10-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smzdmresult',
            name='sentiment',
            field=models.FloatField(),
        ),
    ]
